# Generated by Django 5.2.8 on 2025-11-15 19:55

import apps.core.validators
import apps.users.managers
import apps.users.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(choices=[('AZUAY', 'Azuay'), ('BOLIVAR', 'Bolívar'), ('CANAR', 'Cañar'), ('CARCHI', 'Carchi'), ('COTOPAXI', 'Cotopaxi'), ('CHIMBORAZO', 'Chimborazo'), ('EL_ORO', 'El Oro'), ('ESMERALDAS', 'Esmeraldas'), ('GUAYAS', 'Guayas'), ('IMBABURA', 'Imbabura'), ('LOJA', 'Loja'), ('LOS_RIOS', 'Los Ríos'), ('MANABI', 'Manabí'), ('MORONA_SANTIAGO', 'Morona Santiago'), ('NAPO', 'Napo'), ('ORELLANA', 'Orellana'), ('PICHINCHA', 'Pichincha'), ('PASTAZA', 'Pastaza'), ('SANTA_ELENA', 'Santa Elena'), ('SANTO_DOMINGO_DE_LOS_TSACHILAS', 'Santo Domingo de los Tsáchilas'), ('SUCUMBIOS', 'Sucumbíos'), ('TUNGURAHUA', 'Tungurahua'), ('ZAMORA_CHINCHIPE', 'Zamora Chinchipe')], max_length=50, verbose_name='Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Neighborhood')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complement')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='Default shipping address')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='Default billing address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['user', '-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, help_text='Maximum size: 5MB. Allowed formats: .jpg, .jpeg, .png', upload_to=apps.users.utils.get_user_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.core.validators.FileSizeValidator(max_size=5, unit='MB')], verbose_name='Profile picture')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='es', max_length=10, verbose_name='Language preference')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
